# Generated by Django 5.2 on 2025-04-14 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_enrolled_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
